### ISSUE TITLE
Bubblesort runtime speed

### ISSUE THREAD

**Issue by hiimkoin** [Neatoro/node-sorter#2]
Hi,

I've measured execution time on your Bubblesort's while loop vs just 2 nested for loops and got >10% improvement. Might wanna check that :) Gz to your first node module btw 👍

**Comment by Neatoro** [comment]
Hey hiimkoin,

thanks for your research, will try to adapt it :)

**Comment by Neatoro** [comment]
Fixed in commit
#7673aa3af25e9acb621868ad815c934b593832cf
